export const GET_MOVIES_START = 'GET_MOVIES_START';
export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS';
export const GET_MOVIES_FAILURE = 'GET_MOVIES_FAILURE';

export const GET_SEANCE_START = 'GET_SEANCE_START';
export const GET_SEANCE_SUCCESS = 'GET_SEANCE_SUCCESS';
export const GET_SEANCE_FAILURE = 'GET_SEANCE_FAILURE';

export const BOOK_TICKET_START = 'BOOK_TICKET_START';
export const BOOK_TICKET_SUCCESS = 'BOOK_TICKET_SUCCESS';
export const BOOK_TICKET_FAILURE = 'BOOK_TICKET_FAILURE';

export const CLEAR_MESSAGE_START = 'CLEAR_MESSAGE_START';
export const CLEAR_MESSAGE_SUCCESS = 'CLEAR_MESSAGE_SUCCESS';
export const CLEAR_MESSAGE_FAILURE = 'CLEAR_MESSAGE_FAILURE';

export const CLEAR_SEANCE_START = 'CLEAR_SEANCE_START';
export const CLEAR_SEANCE_SUCCESS = 'CLEAR_SEANCE_SUCCESS';
export const CLEAR_SEANCE_FAILURE = 'CLEAR_SEANCE_FAILURE';